
!*****************************************************************************
!                                                                            *
!        Utilities for use with user-written models for MODSIM               *
!                                                                            *
! (C) MODSIM copyright R P King 2002                                         *
!                                                                            *
!*****************************************************************************

Subroutine ReportHeader(ioUnit,Heading,Model)
!********************************************
!Writes the report header at the top of each unit model report file.
  USE GLOBALS
  USE ModelVariables
	CHARACTER*4 Model
	CHARACTER*(*) Heading
  CHARACTER*1 ULINE(80)
	INTEGER PathLength,JobNameLength,NC
	LOGICAL od
	INTEGER ioUnit
  NC = LEN_TRIM(Heading)
  JobNameLength = LEN_TRIM(JobName)
  Do I = 1,NC
    ULINE(I) = '*'
  End Do

	!Re-open the report file if necessary
	ioUnit = 9
	PathLength = LEN_TRIM(UnitJobPath)
	INQUIRE(FILE = UnitJobPath(1:PathLength)//'REPORT2.OUT', OPENED = od)
	If(.NOT. od) Then
	  OPEN(ioUnit,FILE = UnitJobPath(1:PathLength)//'REPORT2.OUT', ACCESS = 'APPEND')
  End If

  Write(ioUnit,*)
	Write(ioUnit,*)
  Write(ioUnit,*)'UNIT EQUIPMENT DATA SHEET - '//Heading
  Write(ioUnit,1003)(ULINE(I),I=1,NC)
  1003 FORMAT(' ****************************',50A1)
  Write(ioUnit,1004) UnitNumber,Model
  1004 FORMAT(/'     Unit number',I4,10X,' MODSIM model name ',A4)
  Write(ioUnit,1001) (JobName(I:I),I = 1,JobNameLength)
  1001 FORMAT('       Job name: ',80A1)
End Subroutine

Subroutine Diagnostic(DMessage)
!******************************
!Writes a diagnostic message that is generated by a user model subroutine.
  USE GLOBALS
	USE ModelVariables
	USE MSFLIB
	INTEGER L
	LOGICAL od
	CHARACTER*256 DMessage
	INTEGER*4 result

	!Re-open the user diagnostic file if necessary
	ioUnit = 14
	PathLength = LEN_TRIM(UnitJobPath)
	INQUIRE(FILE = UnitJobPath(1:PathLength)//'UserDiagFile.txt', OPENED = od)
	If(.NOT. od) Then
	  OPEN(ioUnit,FILE = UnitJobPath(1:PathLength)//'UserDiagFile.txt')
		NumberOfMessages = 0
  End If

  L = LEN_TRIM(DMessage)
	write(ioUnit,*)DMessage(1:L)
  result = COMMITQQ(ioUnit)
	NumberOfMessages = NumberOfMessages + 1
End

Real Function VolumeFraction(Solids,Water)
!*****************************************
!Calculates the volume fraction of solids in a stream
USE GLOBALS
USE ModelVariables
REAL Solids(NumSizeClasses,NumGClasses,NumSClasses)
REAL SolidVolume
SolidVolume = 0.0
Do I = 1,NumSizeClasses
  Do J = 1,NumGClasses
	  Do K = 1,NumSClasses
      SolidVolume = SolidVolume + Solids(I,J,K)/SolidSpGr(J)
    End Do
  End Do
End Do
If(SolidVolume + Water .LE. 0.0 ) Then
  Call Diagnostic(' Cannot calculate solid volume fraction')
	VolumeFraction = 0.0
	RETURN
End If
VolumeFraction = SolidVolume/(SolidVolume + Water)
END


Real Function VolumeFlow(Solids,Water)
!*************************************
!Calculates the volume flowrate of a stream
USE ModelVariables
REAL Solids(NumSizeClasses,NumGClasses,NumSClasses),Water
REAL SolidVolume
SolidVolume = 0.0
Do I = 1,NumSizeClasses
  Do J = 1,NumGClasses
	  Do K = 1,NumSClasses
      SolidVolume = SolidVolume + Solids(I,J,K)/SolidSpGr(J)
    End Do
  End Do
End Do
VolumeFlow = 0.001*(SolidVolume + Water)
END
