
#This is the NMAKE file that constructs the fixed dimension code
#Only source code that has been modified since the last system setup will
#be compiled.
All: dminp.for report.for pphi5.for

#Include new models if necessary.

pphi5.FOR: parset.for ..\modsimvb\plant.dat "MODELVARIABLES.F90"
    FL32  parset.for
    parset
    erase parset.exe

#Change maximum problem size if necessary.
dminp.FOR: diminp.for
    FL32 diminp.for
    diminp
    erase diminp.exe

report.FOR: diminp.for
    FL32 diminp.for
    diminp
    erase diminp.exe
