C*******************       UNITS.FOR      *****************************C
C                                                                      C
C          MODSIM   MODULAR SIMULATOR FOR ORE DRESSING PLANTS          C
C                                                                      C
C  THIS FILE CONTAINS USER SUPPLIED MODELS FOR MODSIM                  C
C  This file is from Claudio schneider.                                C
C  MODSIM  (C) RP KING  JOHANNESBURG  1985                             C
C                                                                      C
C**********************************************************************C
C
      SUBROUTINE SEGB(TMSF,TMS1,TMS2,TMS3,FEED,OUT1,OUT2,OUT3,DER1,DER2,
     *DER3,NDC,NGC,NSC,WTR,WTR1,WTR2,WTR3,SIZE,PARAM,PPROP,INDPP,FL,NPP,
     *GRDM,GRDV,NMIN,NGCM)
C     ******************************************************************
      REAL  FEED(NDC,NGC,NSC),OUT1(NDC,NGC,NSC),OUT2(NDC,NGC,NSC)
      REAL  OUT3(NDC,NGC,NSC)
      REAL  DER1(NDC,NGC,NSC),DER2(NDC,NGC,NSC),DER3(NDC,NGC,NSC)
      REAL PARAM(*),PPROP(1)
      REAL SIZE(1),GRDM(NGCM,NMIN),GRDV(NGCM,NMIN)
      INTEGER FL,INDPP(NPP,2)
      COMMON NPLNT,NUNIT,ITER,IW,IFLAG
C
C     MODEL TO DESCRIBE SEGREGATION IN SURGE BINS AT ROSSING URANIUM LTD
C
C     PARAMETERS IN ORDER
C     *******************
C 1.....SMALL SIZE ASYMPTOTE
C 2.....RECOVERY OF INTERMEDIATE SIZES
C 3.....CRITICAL SIZE
C 4.....SLOPE OF LOGARITHMIC PORTION
      NOPAR=4
      B1 = PARAM(1)
      B2 = PARAM(2)
      B3 = PARAM(3)
      B4=PARAM(4)
      TMS1 = 0.0
      DO 20 I = 1,NDC
      IF (SIZE(I).LE.0.01) REC = B1
      IF(SIZE(I).GT.0.01.AND.SIZE(I).LE.B3)REC=B2
      IF (SIZE(I).GT.B3) REC = B2 - B4*ALOG(SIZE(I)/B3)
      DO 20 J = 1,NGC
      DO 20 K = 1,NSC
      OUT2(I,J,K) = REC*FEED(I,J,K)
      OUT1(I,J,K) = FEED(I,J,K) - OUT2(I,J,K)
      DER2(I,J,K) = REC
      DER1(I,J,K) = 1.0 - REC
      TMS1 = TMS1 + OUT1(I,J,K)
  20  CONTINUE
      TMS2 = TMSF - TMS1
      WTR1 = B2*WTR
      WTR2=WTR-WTR1
      FL = 1
      RETURN
      END
C
C
      SUBROUTINE UMIL(TMSF,TMS1,TMS2,TMS3,FEED,OUT1,OUT2,OUT3,DER1,DER2,
     *DER3,NDC,NGC,NSC,WTR,WTR1,WTR2,WTR3,SIZE,PARAM,PPROP,INDPP,FL,NPP,
     *GRDM,GRDV,NMIN,NGCM)
C     ******************************************************************
C  MODEL FOR A BALL MILL USING THREE PERFECTLY MIXED REGIONS IN SERIES.
C  NO CLASSIFICATION BETWEEN STAGES, POST-CLASSIFICATION OPTIONAL.
C  PARAMETERS:
C     1....RESIDENCE TIME IN THE FIRST PERFECT MIXED REGION.
C     2....RESIDENCE TIME IN THE SECOND PERFECT MIXED REGION.
C     3....RESIDENCE TIME IN THE THIRD PERFECT MIXED REGION.
C     4....FUNCTIONAL FORM CHOSEN:
C            1 = 3 PAR. BREAK. & 4 PAR. RATE W/O POST CLASSIFICATION
C            2 = 3 PAR. BREAK. & 4 PAR. RATE W/  POST CLASSIFICATION
C            3 = 4 PAR. BREAK. & 4 PAR. RATE W/  POST CLASSIFICATION
C     5....Liberation model chosen
c            0 = None
c	       1 = Ljubljana
c	       2 = Schneider beta function.
C
      USE GLOBALS
      REAL FEED(NDC,NGC,NSC)
      REAL OUT1(NDC,NGC,NSC),OUT2(NDC,NGC,NSC),OUT3(NDC,NGC,NSC)
      REAL DER1(NDC,NGC,NSC),DER2(NDC,NGC,NSC),DER3(NDC,NGC,NSC)
      REAL GRDM(NGCM,NMIN),GRDV(NGCM,NMIN)
      REAL SIZE(NDC),PARAM(*),PPROP(1)
      INTEGER INDPP(NPP,2),FL

      COMMON NPLNT,NUNIT,ITER,IW,IFLAG
      COMMON/SCALEUP/OVFILL

      LOGICAL LJUBLJANA, AM_MODEL
      COMMON /LINCOR/PHIA,LJUBLJANA,AM_MODEL

      EXTERNAL SU1,SU2,SU3
      EXTERNAL BU1,BU2,BU3
      EXTERNAL CU0,CU2,CU3
C
      MAXIT = 25
      OVFILL=1.0
      NFUNC=NINT(PARAM(4))
      SUMTAU=PARAM(1)+PARAM(2)+PARAM(3)
	IF (NINT(PARAM(5)) .EQ. 0) Then
        LJUBLJANA = .FALSE.
        AM_MODEL = .FALSE.
      ELSE IF (NINT(PARAM(5)) .EQ. 1) Then
        LJUBLJANA = .TRUE.
        AM_MODEL = .FALSE.
      ELSE IF (NINT(PARAM(5)) .EQ. 2) Then
        LJUBLJANA = .FALSE.
        AM_MODEL = .TRUE.
      END IF
      DER1 = 1.0
      DTBDF=0.0
      WS = SUM(FEED)
C
C  CALCULATE PRODUCT OF FIRST PERFECT MIXED REGION
C
      NCALL=1
      TAU=PARAM(1)
      IF(TAU .LE. 0.0) THEN
        OUT3 = FEED
      ELSE
        IF(NFUNC.EQ.1)
     *  CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
        IF(NFUNC.EQ.2)
     *  CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
        IF(NFUNC.EQ.3)
     *  CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
        WS = SUM(OUT3)
      END IF
C
C  CALCULATE PRODUCT OF SECOND PERFECT MIXED REGION
C
      NCALL=2
      TAU=PARAM(2)
      IF(TAU .LE. 0.0) THEN
        OUT2 = OUT3
      ELSE
        IF(NFUNC.EQ.1)
     *  CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
        IF(NFUNC.EQ.2)
     *  CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
        IF(NFUNC.EQ.3)
     *  CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
      END IF
C
C  CALCULATE PRODUCT OF THIRD PERFECT MIXED REGION
C
      NCALL=3
      IF(NFUNC.EQ.1) THEN
        TAU = PARAM(3)
        CALL PMMILL(OUT2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *  INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
        FFLOW = TMSF
        TMS1 = 0.0
        DO 10 I=1,NDC
     	DO 10 J=1,NGC
     	  DO 10 K=1,NSC
     	  TMS1 = TMS1 + OUT1(I,J,K)
  10    CONTINUE
        GOTO 35
      ENDIF
C
C  LAST STAGE HAS POST-CLASSIFICATION
C
      IF(ITER.EQ.0) TAUPRIME=PARAM(3)
      DO 15 I=1,NDC
	DO 15 J=1,NGC
	  DO 15 K=1,NSC
	  DER2(I,J,K) = OUT2(I,J,K)
   15 CONTINUE
      IT=0
   20 CONTINUE
      TAU=TAUPRIME
      IF(NFUNC.EQ.2)
     *CALL PMMILL(DER2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.3)
     *CALL PMMILL(DER2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
      GFLOW = 0.0
      FFLOW = 0.0
      DO 30 I=1,NDC
	IF(NFUNC.EQ.2) CALL CU2(I,SIZE(I),C)
	IF(NFUNC.EQ.3) CALL CU3(I,SIZE(I),C)
	DO 30 J=1,NGC
	  DO 30 K=1,NSC
	    FFLOW = FFLOW + OUT1(I,J,K)*(1.0-C)
	    GFLOW = GFLOW + OUT1(I,J,K)
	    DER2(I,J,K) = OUT2(I,J,K) + OUT1(I,J,K)*C
   30 CONTINUE
      GBYF = GFLOW/FFLOW
      IT = IT + 1
      RES = ABS(PARAM(3) - TAUPRIME*GBYF)
      WRITE(UnitDiagFile,1001) RES,IT
 1001 FORMAT('   RES = ',T10,F8.6,' AFTER ',T24,I2,
     *' ITERATIONS IN UMIL')                                                   
      IF(RES.LE.1E-5) GOTO 35
      IF(IT.GE.MAXIT) GOTO 35
      TAUPRIME = PARAM(3)/GBYF
      GOTO 20
   35 CONTINUE
C
C  ACCUMULATE HOLDUPS OF FIRST TWO STAGES 
C                                                     
      DO 40 I=1,NDC

      DO 40 J=1,NGC
      DO 40 K=1,NSC
	OUT2(I,J,K)=OUT2(I,J,K)*PARAM(2)+OUT3(I,J,K)*PARAM(1)
   40 CONTINUE
C  
C  CALCULATE PRODUCT OF POSTCLASSIFIER IN THIRD STAGE 
C  AND SAVE MILL PRODUCT IN OUT3
C
      TMS1 = 0.0
      DO 50 I=1,NDC
	IF(NFUNC.EQ.1) CALL CU0(I,SIZE(I),C)
	IF(NFUNC.EQ.2) CALL CU2(I,SIZE(I),C)
	IF(NFUNC.EQ.3) CALL CU3(I,SIZE(I),C)
	DO 50 J=1,NGC
	  DO 50 K=1,NSC
	    OUT3(I,J,K) = OUT1(I,J,K)
	    OUT1(I,J,K)=OUT1(I,J,K)*(1.0-C)
	    TMS1 = TMS1 + OUT1(I,J,K)
   50 CONTINUE
      WTR1=WTR
      FL=1

C
C
      RETURN
      END
C
C
      SUBROUTINE CU0(I,SIZE,C)
C     **************************
C     CLASSIFICATION FUNCTION FOR NO CLASSIFICATION IN PMMILL
C 
      C=0.0
      RETURN
      END    
C
      SUBROUTINE SU1(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR FAIRLANE PLANT TACONITE 
C
      REAL MU,LAMDA
      PARAMETER(S1=1.44054,ALPHA=1.21291,MU=0.00545713014,LAMDA=5.06250)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE BU1(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR FAIRLANE PLANT TANCONITE
C
      PARAMETER(PHI1=0.59948,DELTA=0.0000000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=0.5000
      GAMMA=1.32876
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE SU2_(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR UTAH LIMESTONE 
C
      REAL MU,LAMDA
      PARAMETER(S1=1.55945,ALPHA=0.76831,MU=0.00156710818,LAMDA=2.81047)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE BU2_(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR UTAH LIMESTONE
C
      PARAMETER(PHI1=0.84144,DELTA=0.00000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=2.91816
      GAMMA=1.38461
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE CU2_(I,SIZE,C)
C     **************************
C     CLASSIFICATION FUNCTION FOR THE 16"X16" OVERFLOW BALL MILL
C 
      PARAMETER(D50=0.00090632980,RO=2.20822)
      CLS(X)=1.0/(1.0+(D50/X)**RO)
      C=CLS(SIZE)
      RETURN
      END    
C
      SUBROUTINE SU2(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR UTAH LIMESTONE 
C  SOLID RTD
C
      REAL MU,LAMDA
      PARAMETER(S1=0.26015,ALPHA=1.19798,MU=0.00149421009,LAMDA=2.40181)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE BU2(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR UTAH LIMESTONE
C  SOLID RTD
C
      PARAMETER(PHI1=0.50153,DELTA=0.00000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=0.44145
      GAMMA=1.71416
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE CU2(I,SIZE,C)
C     **************************
C     CLASSIFICATION FUNCTION FOR THE 16"X16" OVERFLOW BALL MILL
C     SOLID RTD
C
      PARAMETER(D50=0.00398528562,RO=0.10019)
      CLS(X)=1.0/(1.0+(D50/X)**RO)
      C=CLS(SIZE)
      RETURN
      END    
C
      SUBROUTINE SU3(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR UTAH LIMESTONE 
C
      REAL MU,LAMDA
      PARAMETER(S1=1.76712,ALPHA=0.66580,MU=0.00176326119,LAMDA=3.19525)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE BU3(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR UTAH LIMESTONE
C
      PARAMETER(PHI1=0.19946,DELTA=0.10977)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=2.65760
      GAMMA=1.40238
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE CU3(I,SIZE,C)
C     **************************
C     CLASSIFICATION FUNCTION FOR THE 16"X16" OVERFLOW BALL MILL
C 
      PARAMETER(D50=0.00091789461,RO=1.97007)
      CLS(X)=1.0/(1.0+(D50/X)**RO)
      C=CLS(SIZE)
      RETURN
      END
C
      SUBROUTINE KSU1(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR KENNECOTT ORE
C
      REAL MU,LAMDA
      PARAMETER(S1=0.14850,ALPHA=2.16689,MU=0.00062568463,LAMDA=2.16736)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE KBU1(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR KENNECOTT ORE
C
      PARAMETER(PHI1=0.71923,DELTA=0.0000000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=0.60571
      GAMMA=0.54215
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE KSU2(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR KENNECOTT COPPER
C
      REAL MU,LAMDA
      PARAMETER(S1=0.14786,ALPHA=2.12386,MU=0.00057605324,LAMDA=2.15997)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE KBU2(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR KENNECOTT COPPER
C
      PARAMETER(PHI1=0.80182,DELTA=0.00000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=1.13208
      GAMMA=0.50877
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
C
      SUBROUTINE KCU2(I,SIZE,C)
C     **************************
C     CLASSIFICATION FUNCTION FOR THE KENNECOTT OVERFLOW BALL MILL
C 
      PARAMETER(D50=0.00512782195,RO=0.49990)
      CLS(X)=1.0/(1.0+(D50/X)**RO)
      C=CLS(SIZE)
      RETURN
      END    
C     
      SUBROUTINE SF1(I,SIZE,S)
C     ***************************
C  4 PARAMETER SELECTION FUNCTION FOR FAIRLANE PLANT TACONITE 
C
      REAL MU,LAMDA
      PARAMETER(S1=1.44054,ALPHA=1.21291,MU=0.00545713014,LAMDA=5.06250)
      SEL(X)=(S1*(X/0.001000)**ALPHA)/(1.0+(X/MU)**LAMDA)
      S=SEL(SIZE)
      RETURN
      END
C
      SUBROUTINE BF1(I,J,SJ1,SJ2,SI,DELB)
C     **************************************
C  4 PARAMETER BREAKAGE FUNCTION FOR FAIRLANE PLANT TACONITE
C
      PARAMETER(PHI1=0.59948,DELTA=0.0000000)
      PHIFUNC(X) = PHI1*(X/0.001000)**(-DELTA)
      BETA=0.50000
      GAMMA=1.32876
      PHI = PHIFUNC(SI)
      IF(PHI.GT.1.0) PHI = 1.0      
      SR1=SJ1/SI
      SR2=SJ2/SI
      DELB=PHI*(SR1**GAMMA-SR2**GAMMA)+(1.0-PHI)*(SR1**BETA-SR2**BETA)
      RETURN
      END
