C*******************   PROGRAM ORDER	*******************************C
C                                                                      C
C THIS PROGRAM DECOMPOSES THE FLOWSHEET AND ESTABLISHES THE CALCULATIONC
C ORDER                                                                C
C                                                                      C
C  MODSIM  (C) COPYRIGHT  RP KING AND MA FORD JOHANNESBURG  1985       C
C                                                                      C
C**********************************************************************C
C
      SUBROUTINE ORDER(SCM,NSSM,NCYG,
     *WT,UNIT,UNOUT,STRM,STRVEC,INDSV,INVSV,INDISV,NOUT,IOUT,
     *PATH,
     *CYCVEC,INDCYC,NINPU,NINPN,NODINP,NODOUT,INDN,CYCGRP,INDCG,
     *GRPVEC,INDGRP,NODUNT,
     *PLINP,NDINAV,UNINAV,TEAR,INDT,ORDUNT,INDORD,B,E,G,PLOUT
     *,STRCYC,GRSTCY,M,
     *BLOCK,CIRCUT,PATHST,USEDST,USEDCY,STRGRP,UNTGRP,COEF,INDNP,
     *PTHVEC,INDPTH,PTHI,BLANK,NODFED,INDVAL,INDFT,
     *JobPath,ExitValue,DiagFile)

      USE MSFLIB

      CHARACTER*255 JobPath
      INTEGER*4 ExitValue,DiagFile
      INTEGER*2 COEF(1),INDNP(1),PTHVEC(1),INDPTH(1),PTHI(1),BLANK(1),NO
     *DFED(1),INDVAL(1),INDFT(1)
      INTEGER*2 SCM(NSSM,3),WT(1),UNIT(1),UNOUT(1),STRM(1),STRVEC(1),IND
     *SV(1),INVSV(1),INDISV(1)
      INTEGER*2 NOUT(1),IOUT(1),PATH(1),CYCVEC(1)
      INTEGER*2 INDCYC(1),NINPU(1),NINPN(1),NODINP(1),NODOUT(1),INDN(1),
     *CYCGRP(1),INDCG(1),GRPVEC(1)
      INTEGER*2 INDGRP(1),NODUNT(1),PLINP(1),NDINAV(1),UNINAV(1),TEAR(1)
     *,INDT(1),ORDUNT(1),INDORD(1)
      INTEGER*2 B(1),E(1),G(1),PLOUT(1)
      INTEGER STRCYC(1),GRSTCY(1),M(1)
      LOGICAL BLOCK(1),CIRCUT(1),PATHST(1),USEDST(1),USEDCY(1),STRGRP(
     *1),UNTGRP(1)
C
      INTEGER*4 I,J,K,L,M1,M2,N1,N2,IR,IW,IC,IG,IO,IS,INA,IUA,IWT,IORD,P
     *OS,POS1,POSG,PSN,PSN1,NCUR,UCUR,LNUM,GRNUM,LP,STR,UNT,UNTO,UNTS,NO
     *DE,NODS,FL1,FL2,STIN,STOUT,CYC,RV,BASEST,TESTST,NCM,NST,NGS,GN
      INTEGER*4 NGRS,SNUM,NT,NSG,NCG,F,NS,NU,NSM,NUM,NCYG,NC,NG,NPINP,
     *NTT,IA,NNOD,WTCRIT,TS(35)
      INTEGER*4 CCYC,II,NSTATE,MM,P,Q
      INTEGER*4 FL,PTH,PTOT
      INTEGER*4 DIMPT,DIMPTM,DIMAL,DIMALM,DIMFT,DIMFTM,DIMVAL,DIMVLM,DIM
     *SV,DIMSVM,DIMISV,DIMIVM
      CHARACTER*12 FILENAME
      LOGICAL*4 result
C
C
C *PROGRAM TO FIND UNIT CALCULATION ORDER
C ***************************************
C
C Report arrival to the diagnostic file
      WRITE(DiagFile,'(''In the ordering subroutine'')')

C **INITIALIZE
      ExitValue = -1
      NNODM=1
      NUUM=1
      NTTM=1
      NSMM=1
      NUMM=1
      NPINPM=1
      NPOUTM=1
      NPOUT=1
      NPTHM=1
      NVARM=1
      NTMM=1
      NVTM=1
      NTM=1
      DIMPTM=1
      DIMFTM=1
      DIMVLM=1
      DIMALM=1
      DIMSVM=1
      DIMIVM=1
      IR=5
      IWP=6
      IW=8
      ITERM=4
      LENG = LEN_TRIM(JobPath)
      FILENAME = 'PHI3.DAT'
      OPEN(IR,FILE = JobPath(1:LENG)//'PHI3.DAT',ERR = 9990)
      FILENAME = 'PHO1.DAT'
      OPEN(IWP,FILE = JobPath(1:LENG)//'PHO1.OUT',ERR = 9990)
      FILENAME = 'PHO3.DAT'
      OPEN(IW,FILE = JobPath(1:LENG)//'PHO3.DAT',ERR = 9990)
      TEAR(1)=0
      COEF(1)=0
C
C *READ DATA FROM INPUT PHASE
C
 1000 FORMAT(6I4)
 1001 FORMAT(20I4)
 2000 FORMAT(20I4)
 4    READ(IR,1000,ERR = 9999) NPLT
      IF(NPLT.EQ.0) GO TO 980
      READ(IR,1000,ERR = 9999) NS,NU,NSM,NUM,NVAR
      DO 5 I=1,NS
        READ(IR,1000,ERR = 9999) (SCM(I,J),J=1,3)
 5    CONTINUE
      READ(IR,1000,ERR = 9999) WTCRIT
      READ(IR,1001,ERR = 9999) (WT(I),I=1,NSM)
C
C
C *ALGORITHM TO DETERMINE STRVEC ETC FROM SCM
C *******************************************
C *INITIALIZE
C
      DO 107 I=1,NSM
        UNIT(I)=0
        UNOUT(I)=0
 107  CONTINUE
      DO 108 I=1,NUM
        STRM(I)=0
 108  CONTINUE
C
C *FIND UNIT,STRM,UNOUT
C
      DO 109 I=1,NS
        UNIT(SCM(I,1))=SCM(I,3)
        UNOUT(SCM(I,1))=SCM(I,2)
        IF(SCM(I,3).EQ.0) GO TO 109
        STRM(SCM(I,3))=SCM(I,1)
 109  CONTINUE
      POS=0
      POS1=0
      NPINP=0
      NPOUT=0
      STR=0
C
C *TAKE NEXT STREAM IF ANY
C
 110  STR=STR+1
      IF(STR.GT.NSM) GO TO 130
      FL1=0
      FL2=0
C
C *FIND UNIT FED BY STR AND
C  UNIT FOR WHICH STR IS OUTPUT
C
      UNT=UNIT(STR)
      IF(UNT.EQ.0) FL1=1
      UNTO=UNOUT(STR)
      IF(UNTO.EQ.0) FL2=1
C
C *CHECK THAT STR IS ACTUALLY A STREAM
C
      IF(FL1.EQ.1.AND.FL2.EQ.1) GO TO 120
C
C
C *IF STR IS PLANT FEED,LIST
C
      IF(FL2.EQ.1) NPINP=NPINP+1
      IF(FL2.EQ.1) PLINP(NPINP)=STR
C
C **IF STREAM IS PLANT OUTPUT LIST
C
      IF(FL1.EQ.1) NPOUT=NPOUT+1
      IF(FL1.EQ.1) PLOUT(NPOUT)=STR
C
C *USE EACH ROW OF SCM TO GIVE NEXT ELEMENTS
C
      DO 119 I=1,NS
        IF(UNT.EQ.0) GO TO 118
        IF(SCM(I,2).NE.UNT) GO TO 118
        POS=POS+1
        STRVEC(POS)=SCM(I,1)
 118    IF(UNTO.EQ.0) GO TO 119
        IF(SCM(I,3).NE.UNTO) GO TO 119
        POS1=POS1+1
        INVSV(POS1)=SCM(I,1)
 119  CONTINUE
 120  INDSV(STR)=POS
      INDISV(STR)=POS1
      GO TO 110
 130  CONTINUE
C
      DIMSV=POS
      DIMISV=POS1
      IF(DIMSV.GT.DIMSVM) DIMSVM=DIMSV
      IF(DIMISV.GT.DIMIVM) DIMIVM=DIMISV
C
C
C *ALGORITHM TO FIND ALL CYCLES IN PLANT
C **************************************
C
C   GET NOUT FROM INDSV
C
      NOUT(1)=INDSV(1)
      STRCYC(1)=0
      DO 9 I=2,NSM
        NOUT(I)=INDSV(I)-INDSV(I-1)
        STRCYC(I)=0
 9    CONTINUE
C
C   SET COUNTERS
C
      NC=0
      L=0
      IS=0
      RV=NSM+1
C
C   FIND NEW ROOT VERTEX
C
 10   RV=RV-1
      IF(RV.EQ.0) GO TO 50
      IF(NOUT(RV).EQ.0) GO TO 10
C
C   INITIALIZE FOR EVERY NEW RV
C
      DO 11 I=1,NSM
        BLOCK(I)=.FALSE.
        CIRCUT(I)=.FALSE.
        PATHST(I)=.FALSE.
        IOUT(I)=0
 11   CONTINUE
C
C      write(DiagFile,*)' Start path'
C   START PATH
C
      J=1
      PATH(J)=RV
      BASEST=RV
C      write(DiagFile,*)' BASEST',BASEST
C
C   CHECK POSSIBLE EXTENSION
C
 20   IOUT(BASEST)=IOUT(BASEST)+1
      IF(IOUT(BASEST).GT.NOUT(BASEST)) GO TO 40
      IF(BASEST.LE.1) TESTST=STRVEC(IOUT(BASEST))
      IF(BASEST.GT.1) TESTST=STRVEC(INDSV(BASEST-1)+IOUT(BASEST))
      IF(BASEST.GT.1) IZZI=INDSV(BASEST-1)+IOUT(BASEST)
      IF(TESTST.EQ.RV) GO TO 30
      IF(TESTST.GT.RV) GO TO 20
      IF(PATHST(TESTST)) GO TO 20
      IF(BLOCK(TESTST)) GO TO 20
C
c      write(DiagFile,*) 'Extend path'
C  EXTEND PATH
C
      J=J+1
      PATH(J)=TESTST
      PATHST(TESTST)=.TRUE.
C      BLOCK(TESTST)=.TRUE.
      BASEST=TESTST
      GO TO 20
C
C   RECORD CIRCUIT
C
 30   CONTINUE
      K=1
c      write(Diagfile,*)' Circuit recorded'
      L=L+1
      NC=L
 31   IS=IS+1
 2090 FORMAT(10I4)
      CYCVEC(IS)=PATH(K)
c      WRITE(Diagfile,2091)IS,CYCVEC(IS)
c 2091 FORMAT(' CYCVEC(',I3,') =',I5)
      STRCYC(PATH(K))=STRCYC(PATH(K))+2**(L-1)
      K=K+1
      IF(K.LE.J) GO TO 31
      INDCYC(L)=IS
      CIRCUT(BASEST)=.TRUE.
C
C   BACKTRACK
C
 40   Continue
      J=J-1
      IF(J.EQ.0) GO TO 10
      IF(CIRCUT(BASEST)) BLOCK(BASEST)=.FALSE.
      IF(CIRCUT(BASEST)) CIRCUT(PATH(J))=.TRUE.
      PATHST(BASEST)=.FALSE.
      IOUT(BASEST)=0
      BASEST=PATH(J)
      GO TO 20
 50   CONTINUE
C
C     PAUSE 3
C *ALGORITHM TO WEIGHT PLANT STREAMS
C ************************************
C
      IF(WTCRIT.EQ.0) GO TO 730
      IF(NC.EQ.0) GO TO 730
      NCM=INDCYC(NC)
      IF(WTCRIT.EQ.1) IA=1
      IF(WTCRIT.EQ.2) IA=NCM
      DO 710 I=1,NCM
        STR=CYCVEC(I)
        IF(WT(STR).EQ.0) GO TO 710
        WT(STR)=WT(STR)+IA
 710  CONTINUE
      IF(WTCRIT.NE.1) GO TO 730
      DO 720 I=1,NSM
        IF(WT(I).EQ.0) GO TO 720
        WT(I)=WT(I)-1
 720  CONTINUE
 730  CONTINUE
C
C
C *ALGORITHM 2 TO GROUP CYCLES INTO MAXIMAL NETS
C **********************************************
C
C
C *INITIALIZE
C
      NG=0
      IG=0
      IC=0
      K=0
      IF(NC.EQ.0) GO TO 250
      DO 208 I=1,NUM
        NINPU(I)=0
 208  CONTINUE
      DO 209 I=1,NSM
        USEDST(I)=.FALSE.
        IF(I.LE.NC) USEDCY(I)=.FALSE.
 209  CONTINUE
C
C *FIND UNUSED CYCLE TO START NEW GROUP IF ANY
C
C
c      write(DiagFile,*)' In ALGORITHM 2   NC',NC
 210  DO 211 I=1,NC
        IF(USEDCY(I)) GO TO 211
        IC=IC+1
        CYCGRP(IC)=I
        USEDCY(I)=.TRUE.
        GO TO 220
 211  CONTINUE
      GO TO 250
C
C *TEST NEXT CYCLE IN GROUP IF ANY
C
 220  K=K+1
      IF(K.LE.IC) GO TO 230
C
C *COMPLETED GROUP
C
      K=K-1
      NG=NG+1
      INDGRP(NG)=IG
      INDCG(NG)=IC
C      write(*,*)' NG,INDCG(NG)',NG,INDCG(NG)
      GO TO 210
C
C *FIND NUMBER OF STREAMS IN CYCLE
C
 230  IF(CYCGRP(K).LE.1) NST=INDCYC(1)
      IF(CYCGRP(K).GT.1) NST=INDCYC(CYCGRP(K))-INDCYC(CYCGRP(K)-1)
C
C *TEST NEXT STREAM OF CYCLE(STR) IF ANY
C
      POS1=INDCYC(CYCGRP(K))
      POS=POS1-NST
 231  POS=POS+1
      IF(POS.GT.POS1) GO TO 220
      STR=CYCVEC(POS)
C
C *CHECK IF STR UNUSED
C
      IF(USEDST(STR)) GO TO 231
C
C *ADD STR TO GROUP
C
      IG=IG+1
      GRPVEC(IG)=STR
C      write(*,*)' IG,GRPVEC(IG)',IG,GRPVEC(IG)
      USEDST(STR)=.TRUE.
      IF(UNIT(STR).NE.0) NINPU(UNIT(STR))=NINPU(UNIT(STR))+1
C
C *TEST NEXT CYCLE IN PLANT IF ANY
C
      L=0
 240  L=L+1
      IF(L.GT.NC) GO TO 231
C
C *CHECK IF CYCLE UNUSED
C
cC      write(*,*)' L,USEDCY(L)',L,USEDCY(L)
      IF(USEDCY(L)) GO TO 240
C
C *CHECK STR OPENS THIS CYCLE
C
      IF(MOD(STRCYC(STR)/2**(L-1),2).EQ.0) GO TO 240
C
C *ADD CYCLE TO GROUP
C
      IC=IC+1
      CYCGRP(IC)=L
      USEDCY(L)=.TRUE.
      GO TO 240
 250  CONTINUE
C      write(*,2250) NG,(INDGRP(I),I=1,NUM)
 2250 FORMAT(' NG=',I5/' INDGRP:'/(20I4))
C      write(*,2251) (CYCGRP(I),I=1,NSSM)
 2251 FORMAT(' CYCGRP:'/(20I4))
C
C
C *ALGORITHM 3 TO RECORD INPUTS & OUTPUTS FOR EVERY NODE
C ******************************************************
C
C
C *INITIALIZE
C
      DO 306 J=1,NSM
        NODINP(J)=0
        STRGRP(J)=.FALSE.
 306  CONTINUE
      NGS=0
      IF(NG.NE.0) NGS=INDGRP(NG)
      IF(NGS.EQ.0) GO TO 305
      DO 307 J=1,NGS
        K=GRPVEC(J)
C      write(*,*)' J,GRPVEC(J)',J,GRPVEC(J)
        STRGRP(K)=.TRUE.
 307  CONTINUE
 305  CONTINUE
      DO 308 J=1,NUM
        UNTGRP(J)=.FALSE.
 308  CONTINUE
      DO 309 J=1,NU
        NINPN(J)=0
 309  CONTINUE
      IO=0
      POS=0
      GN=1
      IF(NG.EQ.0) GN=0
      IF(NG.EQ.0) GO TO 330
C
C
C *TREAT COMPLEX NODES
C      write(*,*)' Treat complex nodes'
C
C *TAKE NEXT STREAM IN GROUP IF ANY
C      write(*,*)' Take next stream in group if any'
C
 310  POS=POS+1
C      write(*,*)' POS',POS
      IF(POS.LE.INDGRP(GN)) GO TO 320
C
C *RECORD END OF CURRENT GROUP
C      write(*,*)' Record end of current group'
C      write(*,*)' '
C
      INDN(GN)=IO
      IF(POS.GT.NGS) GO TO 330
      GN=GN+1
 320  STR=GRPVEC(POS)
C      write(*,*)' POS,GRPVEC(POS)',POS,GRPVEC(POS)
      UNTGRP(UNIT(STR))=.TRUE.
C
C *FIND INPUTS TO THIS STREAM
C
 321  N1=1
      IF(STR.GT.1) N1=INDISV(STR-1)+1
      N2=INDISV(STR)
c      WRITE(9,2331) N1,N2
      DO 322 K=N1,N2
      STIN=INVSV(K)
      IF(STRGRP(STIN)) GO TO 322
      NODINP(STIN)=GN
      NINPN(GN)=NINPN(GN)+1
C      write(*,2332) STIN,GN,NINPN(GN)
 2332 FORMAT(' STIN=',I5,'  GN=',I5,'  NINPN(GN)=',I5)
 322  CONTINUE
C
C *FIND OUTPUTS FROM THIS STREAM
C      write(*,*)' Find output from this stream'
C
      M1=1
      IF(STR.GT.1) M1=INDSV(STR-1)+1
      M2=INDSV(STR)
      DO 323 K=M1,M2
        STOUT=STRVEC(K)
        IF(STRGRP(STOUT)) GO TO 323
        IO=IO+1
        NODOUT(IO)=STOUT
 323  CONTINUE
      GO TO 310
C
C
C *TREAT SIMPLE NODES
C      write(*,*)' treat simple nodes'
C
C *TAKE NEXT STREAM IN PLANT IF ANY
C      write(*,*)' Take next stream in plant if necessary'
C
 330  DO 333 I=1,NSM
C
C *FIND UNIT FED BY STREAM
C      write(*,*)' Find unit fed by steam'
C
        UNT=UNIT(I)
C      write(*,*)' UNT',UNT
C
C *CHECK IF REAL UNIT AND IF ALREADY IN NODE
C      write(*,*)' CHECK IF REAL UNIT AND IF ALREADY IN NODE'
C
        IF(UNT.EQ.0) GO TO 333
        IF(UNTGRP(UNT)) GO TO 333
C
C *PUT UNIT INTO NODE
C      write(*,*)' Put unit into Node'
C
        UNTGRP(UNT)=.TRUE.
        GN=GN+1
        NODUNT(GN)=UNT
C
C *FIND OUTPUTS FROM THIS NODE AND RECORD
C      write(*,*)' FIND OUTPUTS FROM THIS NODE AND RECORD'
C
        M1=1
        IF(I.GT.1) M1=INDSV(I-1)+1
        M2=INDSV(I)
        DO 331 K=M1,M2
          STOUT=STRVEC(K)
          IO=IO+1
          NODOUT(IO)=STOUT
 331    CONTINUE
        INDN(GN)=IO
C
C *FIND INPUTS TO THIS NODE AND RECORD
C      write(*,*)' FIND INPUTS TO THIS NODE AND RECORD'
C
        N1=1
        IF(STOUT.GT.1) N1=INDISV(STOUT-1)+1
        N2=INDISV(STOUT)
C      write(*,2331) N1,N2
 2331   FORMAT(' N1=',I5,'  N2=',I5)
        DO 332 K=N1,N2
          STIN=INVSV(K)
          NODINP(STIN)=GN
          NINPN(GN)=NINPN(GN)+1
 332    CONTINUE
 333  CONTINUE
C
C
C *ALGORITHM  TO GET UNIT ORDER & TEARS FOR THE PLANT
C     PAUSE 6
C ***************************************************
C
C
      INA=0
      NTT=0
      NGRS=0
      IORD=0
C
C *REDUCE INPUTS TO NODES BY FEEDS AND
C  LIST NODES WITH ALL INPUTS
C
      DO 409 I=1,NPINP
      NODE=NODINP(PLINP(I))
      NINPN(NODE)=NINPN(NODE)-1
C      write(*,2409)NODE,NINPN
 2409 FORMAT(' NODE=',I5,'  NINPN=',I5)
      IF(NINPN(NODE).GT.0) GO TO 409
      INA=INA+1
      NDINAV(INA)=NODE
 409  CONTINUE
C
C *TAKE NEXT NODE WITH ALL INPUTS,IF ANY
C
 410  INA=INA-1
      NCUR=INA+1
      IF(NCUR.LE.0) GO TO 440
      NODE=NDINAV(NCUR)
C
C *CHECK IF COMPLEX NODE
C
      IF(NODE.LE.NG) GO TO 420
C
C *ADD SIMPLE NODE TO UNIT ORDER
C
      NGRS=NGRS+1
C      write(*,2410) NGRS
 2410 FORMAT(' NGRS=',I4)
      IF(NGRS.EQ.1) INDT(NGRS)=0
      IF(NGRS.NE.1) INDT(NGRS)=INDT(NGRS-1)
      IORD=IORD+1
      UNT=NODUNT(NODE)
      ORDUNT(IORD)=UNT
C
C *INDEX END OF NODE
C
415   INDORD(NGRS)=IORD
C
C * REDUCE INPUTS TO NODES FED BY THIS NODE
C AND LIST THOSE WITH ALL INPUTS NOW AVAILABLE
C
      N1=1
      IF(NODE.NE.1) N1=INDN(NODE-1)+1
      N2=INDN(NODE)
      DO 416 I=N1,N2
      STOUT=NODOUT(I)
      NODS=NODINP(STOUT)
      IF(NODS.EQ.0) GO TO 416
      NINPN(NODS)=NINPN(NODS)-1
      IF(NINPN(NODS).NE.0) GO TO 416
      INA=INA+1
      NDINAV(INA)=NODS
 416  CONTINUE
      GO TO 410
C
C
C *FIND TEARS FOR COMPLEX NODE
C
 420  GRNUM=NODE
C
C *ALGORITHM TO RENUMBER STREAMS & CYCLES WITHIN GROUPS
C     PAUSE 7
C $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C
C
C *FIND NUMBER STREAMS & CYCLES IN GROUP
C
      IF(GRNUM.LE.1) NSG=INDGRP(1)
      IF(GRNUM.GT.1) NSG=INDGRP(GRNUM)-INDGRP(GRNUM-1)
      IF(GRNUM.LE.1) NCG=INDCG(1)
      IF(GRNUM.GT.1) NCG=INDCG(GRNUM)-INDCG(GRNUM-1)
      IWT=0
      DO 509 I=1,NSG
      GRSTCY(I)=0
 509  CONTINUE
C
C *TAKE NEXT STREAM IN GROUP IF ANY
C
      POS1=INDGRP(GRNUM)-NSG
      POS=POS1
 510  POS=POS+1
      IF(POS.GT.INDGRP(GRNUM)) GO TO 530
C
C *RENUMBER WEIGHTS
C
      IWT=IWT+1
      B(IWT)=WT(GRPVEC(POS))
C
C *TAKE COLLECTION OF CYCLES OPENED BY STREAM
C
      CCYC=STRCYC(GRPVEC(POS))
C    WRITE(9,*) GRPVEC(POS)
C
C *TAKE NEXT CYCLE IN GROUP IF ANY
C
      PSN1=INDCG(GRNUM)-NCG
      PSN=PSN1
 520  PSN=PSN+1
      IF(PSN.GT.INDCG(GRNUM)) GO TO 510
      CYC=CYCGRP(PSN)
C
C *CHECK IF THIS CYCLE IS OPENED BY STREAM
C
C      write(*,8130) CCYC,CYC,PSN
 8130 FORMAT(' CCYC=',I10,' CYC=',I5, '  PSN=',I5)
      IF(MOD(CCYC/2**(CYC-1),2).EQ.0) GO TO 520
C
C * STORE IN COLLECTION OF RENUMBERED CYCLES
C  OPENED BY RENUMBERED STREAMS
C
      LNUM=PSN-PSN1
      SNUM=POS-POS1
      GRSTCY(SNUM)=GRSTCY(SNUM)+2**(LNUM-1)
      GO TO 520
 530  CONTINUE
C
C
C *ALGORITHM TO FIND TEAR STREAMS OF GROUP
C     PAUSE 8
C $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
C
C
C *INITIALIZE
C
C      write(*,2609) NCG
 2609 FORMAT(' NCG=',I4)
      NSTATE=2**NCG
      IF(NSTATE.GT.NCYG) THEN
        WRITE(Diagfile,2608) NCG
 2608   FORMAT(' THIS PLANT HAS A NODE WITH',I5,' CYCLES.'/
     *' PLEASE RESET VALUE OF NCYC IN PROGRAM DIMINP AND RECOMPILE.')
        GO TO 9991
      END IF
      DO 609 II=1,NSTATE
      E(II)=32001
      G(II)=0
      M(II)=0
 609  CONTINUE
      Q=0
      E(1)=0
C
C *MOVE TO NEXT STATE IF ANY
 610  Q=Q+1
      IF(Q.GE.NSTATE) GO TO 630
C
C *CHECK IF REACHED THIS STATE BEFORE
C
      IF(E(Q).EQ.32001) GO TO 610
C
C *TAKE NEXT LARGEST STREAM IF ANY
C
      L=G(Q)
 620  L=L+1
      IF(L.GT.NSG) GO TO 610
C
C *FIND NEW STATE
C
      MM=0
      DO 621 LP=1,NCG
      IF(MOD(GRSTCY(L)/2**(LP-1),2).EQ.0) GO TO 621
      IF(MOD((Q-1)/2**(LP-1),2).EQ.1) GO TO 621
      MM=MM+2**(LP-1)
 621  CONTINUE
C    WRITE(9,2621) L,Q,P
 2621 FORMAT(' L=',I4,' Q=',I4,' P=',I4)
      P=Q+MM
C
C *CALCULATE COST FOR NEW STATE & COMPARE
C
      F=E(Q)+B(L)
      IF(E(P).LE.F) GO TO 620
C
C *RESET COST & INDEX
C
      G(P)=L
      E(P)=F
      M(P)=Q
      GO TO 620
C
C *GET TEAR STREAMS
C
 630  Q=NSTATE
      DO 631 NT=1,NCG
      TS(NT)=G(Q)
      Q=M(Q)
      IF(Q.EQ.1) GO TO 640
 631  CONTINUE
 640  CONTINUE
      IF(NT.GT.NTM) NTM=NT
C
C
C *CONTINUATION OF ORDER
C **********************
C
C *REDUCE INPUTS TO UNITS BY TEARS AND
C  LIST UNITS WITH ALL INPUTS
C
      IF(GRNUM.EQ.1) POSG=0
      IF(GRNUM.NE.1) POSG=INDGRP(GRNUM-1)
      IUA=0
      DO 421 I=1,NT
      NTT=NTT+1
      TEAR(NTT)=GRPVEC(POSG+TS(I))
      UNT=UNIT(TEAR(NTT))
      NINPU(UNT)=NINPU(UNT)-1
      IF(NINPU(UNT).GT.0) GO TO 421
      IUA=IUA+1
      UNINAV(IUA)=UNT
 421  CONTINUE
      NGRS=NGRS+1
      IF(NGRS.EQ.1) INDT(NGRS)=NT
      IF(NGRS.NE.1) INDT(NGRS)=INDT(NGRS-1)+NT
C
C *TAKE NEXT UNIT WITH ALL INPUTS IF ANY
C
 430  IUA=IUA-1
      UCUR=IUA+1
      IF(UCUR.LE.0) GO TO 415
C
C *ADD THIS UNIT TO UNIT ORDER
C
      UNT=UNINAV(UCUR)
      IORD=IORD+1
      ORDUNT(IORD)=UNT
C
C *REDUCE INPUTS TO UNITS FED BY THIS UNIT AND
C  LIST THOSE WITH ALL INPUTS AVAILABLE
C
      N1=1
      STR=STRM(UNT)
      IF(STR.NE.1) N1=INDSV(STR-1)+1
      N2=INDSV(STR)
      DO 431 I=N1,N2
      IF(.NOT.STRGRP(STRVEC(I))) GO TO 431
      UNTS=UNIT(STRVEC(I))
      NINPU(UNTS)=NINPU(UNTS)-1
      IF(NINPU(UNTS).NE.0) GO TO 431
      IUA=IUA+1
      UNINAV(IUA)=UNTS
 431  CONTINUE
      GO TO 430
 440  CONTINUE
      NNOD=NGRS
C    WRITE(9,2440) NNOD
 2440 FORMAT(' NNOD=',I4)
C
C
C
C **ALGORITHM TO FIND PATHS IN EACH NODE OF PLANT
C     PAUSE 9
C ************************************************
C
C
C **INITIALIZE
C
      DO 909 I=1,NSM
      IOUT(I)=0
      INDPTH(I)=0
      PTHVEC(I)=0
 909  CONTINUE
      IP=0
      NODE=0
C
C **TAKE NEXT NODE IF ANY
C
 910  NODE=NODE+1
      IF(NODE.GT.NNOD) GO TO 960
C
C **INDEX PATH IN NODE
C
      IF(NODE.NE.1) INDNP(NODE-1)=IP
C
C **FIND POSITION OF TEARS IF ANY
C
      L1=0
      IF(NODE.NE.1) L1=INDT(NODE-1)
      L2=INDT(NODE)
      LS=L1+1
      NT=L2-L1
      IF(NT.EQ.0) GO TO 910
C
C **TAKE NEXT TEAR AS ROOT VERTEX
C
 920  L1=L1+1
      IF(L1.GT.L2) GO TO 910
      RV=TEAR(L1)
      J=1
      PATH(1)=RV
      BASEST=RV
C
C **TAKE NEXT OUTPUT OF BASEST IF ANY
C
 930  IOUT(BASEST)=IOUT(BASEST)+1
      IF(IOUT(BASEST).LE.NOUT(BASEST)) GO TO 940
C
C **BACKTRACK
C
      J=J-1
      IF(J.EQ.0) GO TO 920
      IOUT(BASEST)=0
      BASEST=PATH(J)
      GO TO 930
C
C **FIND TESTST AND CHECK THAT MEMBER OF COMPLEX NODE
C
 940  IF(BASEST.LE.1) TESTST=STRVEC(IOUT(BASEST))
      IF(BASEST.GT.1) TESTST=STRVEC(INDSV(BASEST-1)+IOUT(BASEST))
      IF(.NOT.STRGRP(TESTST)) GO TO 930
C
C **CHECK IF TESTST IS A TEAR
C
      DO 941 I=LS,L2
      IF(TESTST.EQ.TEAR(I)) GO TO 950
 941  CONTINUE
C
C **EXTEND PATH
C
      J=J+1
      PATH(J)=TESTST
      BASEST=TESTST
      GO TO 930
C
C **RECORD PATH
C
 950  IP=IP+1
      COEF(IP)=(L1-LS)*NT+I-LS+1
      J=J+1
      PATH(J)=TEAR(I)
      NJ=J
C
C
C **ALGORITHM TO SET UP VECTOR OF PATHS EFFECTED BY EACH STREAM
C     PAUSE 10
C *************************************************************
C
C
C **ORDER MEMBERS OF PATH FROM SMALLEST TO LARGEST
C
C
C **INITIALIZE
C
      POS=0
      FL=0
      J=J-1
      DO 949 I=1,J
      PTHI(I)=PATH(I+1)
 949  CONTINUE
C
C **MOVE TO NEXT STREAM IN PARTIALLY ORDERED PATH IF ANY
C
 951  POS=POS+1
C     PAUSE 951
      IF(POS.GE.J) GO TO 952
      IF(PTHI(POS).LT.PTHI(POS+1)) GO TO 951
C
C **SWOP THESE TWO STREAMS
C
      IF(POS.GT.1) FL=1
      PTH=PTHI(POS+1)
      PTHI(POS+1)=PTHI(POS)
      PTHI(POS)=PTH
      GO TO 951
C
C **CHECK IF MADE A SWOP
C
  952 IF(FL.EQ.0) GO TO 953
C     PAUSE 952
      POS=0
      FL=0
      GO TO 951
C
C **INSERT PATH NUMBER WHICH EFFECTED BY STREAMS
C
C **INITIALIZE
C
 953  STR=NSM+1
C     PAUSE 953
      POS=INDPTH(NSM)
C
C **TAKE NEXT SMALLER STREAM
 954  STR=STR-1
C     PAUSE 954
C
C **ADD NUMBER OF UNPLACED PATH MEMBERS TO INDEX
C
      INDPTH(STR)=INDPTH(STR)+J
C
C **CHECK IF STREAM EQUALS LAST UNPLACED MEMBER OF NEW PATH
C
      IF(STR.EQ.PTHI(J)) GO TO 956
C
C **CHECK IF MOVED ALL MEMBERS ASSOCIATED WITH STREAM
C
 955  IF(POS.EQ.INDPTH(STR-1)) GO TO 954
C     PAUSE 955
C
C **MOVE NEXT MEMBER UP J POSITIONS
C
      PTHVEC(POS+J)=PTHVEC(POS)
C
C **MOVE TO PRECEEDING MEMBER
C
      POS=POS-1
      GO TO 955
C
C **INSERT NEW PATH MEMBER INTO PTHVEC
C
 956  PTHVEC(POS+J)=IP
C     PAUSE 956
C
C **REDUCE J BY 1
C
      J=J-1
C
C **CHECK J=0
C
      IF(J.EQ.0) GO TO 957
      GO TO 955
C
C **OUTPUT
 957  CONTINUE
C     PAUSE 957
C
      J=NJ-1
      GO TO 930
C
C **FIND DIMENSIONS FOR ALFA AND PTHVEC
C
 960  INDNP(NNOD)=IP
C     PAUSE 960
      NOPTM=INDNP(1)
      IF(NNOD.EQ.1) GO TO 962
      DO 961 I=2,NNOD
      NOPT=INDNP(I)-INDNP(I-1)
      IF(NOPT.GT.NOPTM) NOPTM=NOPT
 961  CONTINUE
 962  DIMAL=NOPTM*NVAR
C     PAUSE 962
      IF(DIMAL.GT.DIMALM) DIMALM=DIMAL
      DIMPT=INDPTH(NSM)
      IF(DIMPT.GT.DIMPTM) DIMPTM=DIMPT
      NPTH=IP
      IF(IP.GT.NPTHM) NPTHM=IP
C
C
C
C     PAUSE 11
C **ALGORITHM TO SET UP INDVAL TO POSITION THE STORING OF
C   STREAMS AS THEY ARE CALCULATED
C *******************************************************
C
C
C
C **INITIALIZE
C
      DO 807 I=1,NSM
        INDVAL(I)=0
 807  CONTINUE
      PTOT=NPINP
      IFE=0
      IB=0
      NN=1
      NNM=INDORD(NNOD)
C
C **INSERT PLANT FEEDS
C
      DO 808 I=1,NPINP
        INDVAL(PLINP(I))=I
 808  CONTINUE
C
C **FIND POSITION OF NODE ONE TEARS
C   AND INSERT IF ANY
C
      L1=1
      L2=INDT(1)
      NT=L2-L1+1
      IF(NT.EQ.0) GO TO 810
      DO 809 I=L1,L2
      PTOT=PTOT+1
      INDVAL(TEAR(I))=PTOT
 809  CONTINUE
C
C **TAKE NEXT UNIT IF ANY
C
 810  DO 830 POS=1,NNM
      UNT=ORDUNT(POS)
C
C **CHECK IF STARTING NEW NODE
C
      IF(POS.LE.INDORD(NN)) GO TO 820
C
C **RELEASE OLD NODE FEED AND TEARS
C
      NN=NN+1
      IF(IFE.EQ.0) GO TO 815
      DO 814 I=1,IFE
      IB=IB+1
      BLANK(IB)=NODFED(I)
 814  CONTINUE
      IFE=0
 815  IF(NT.EQ.0) GO TO 817
      DO 816 I=L1,L2
      IB=IB+1
      BLANK(IB)=INDVAL(TEAR(I))
 816  CONTINUE
C
C **FIND POSITION OF NEW NODES
C   TEARS AND INSERT IF ANY
C
 817  L1=INDT(NN-1)+1
      L2=INDT(NN)
      NT=L2-L1+1
      IF(NT.EQ.0) GO TO 820
      DO 819 I=L1,L2
      IF(IB.EQ.0) GO TO 818
      INDVAL(TEAR(I))=BLANK(IB)
      IB=IB-1
      GO TO 819
 818  PTOT=PTOT+1
      INDVAL(TEAR(I))=PTOT
 819  CONTINUE
C
C **FIND POSITION OF UNIT INPUTS & OUTPUTS
C
 820  STR=STRM(UNT)
      N1=1
      IF(STR.NE.1) N1=INDSV(STR-1)+1
      N2=INDSV(STR)
      STR=STRVEC(N1)
      M1=1
      IF(STR.NE.1) M1=INDISV(STR-1)+1
      M2=INDISV(STR)
C
C **RELEASE INPUTS UNLESS FEED OR TEAR FOR THIS NODE
C
      DO 822 I=M1,M2
      IF(NT.EQ.0) GO TO 826
      DO 825 J=L1,L2
      IF(INVSV(I).EQ.TEAR(J)) GO TO 822
 825  CONTINUE
 826  IF(NODINP(INVSV(I)).EQ.0) GO TO 821
      IFE=IFE+1
      NODFED(IFE)=INDVAL(INVSV(I))
      GO TO 822
 821  IB=IB+1
      BLANK(IB)=INDVAL(INVSV(I))
 822  CONTINUE
C
C **INSERT OUTPUTS INTO INDVAL,UNLESS TEAR
C
      DO 824 I=N1,N2
      IF(INDVAL(STRVEC(I)).NE.0) GO TO 824
      IF(IB.EQ.0) GO TO 823
      INDVAL(STRVEC(I))=BLANK(IB)
      IB=IB-1
      GO TO 824
 823  PTOT=PTOT+1
      INDVAL(STRVEC(I))=PTOT
 824  CONTINUE
 830  CONTINUE
C
C **CORRECT INDVAL TO CORRECT POSTION
C
      DO 831 I=1,NSM
      IF(INDVAL(I).EQ.0) GO TO 831
      INDVAL(I)=INDVAL(I)*NVAR-NVAR+1
      !write(*,*)'NVAR',NVAR
 831  CONTINUE
C
C **FIND DIMENSIONS FOR STRVAL
C
      DIMVAL=PTOT*NVAR
      IF(DIMVAL.GT.DIMVLM) DIMVLM=DIMVAL
C
C
C
C **ALGORITHM TO POSITION FEEDS AND TEARS
C     PAUSE 12
C ***************************************
C
      DO 970 I=1,NSM
        INDFT(I)=0
 970  CONTINUE
      DO 971 I=1,NPINP
        INDFT(PLINP(I))=(I-1)*NVAR+1
 971  CONTINUE
      IF(NTT.EQ.0) TEAR(1)=0
      IF(NTT.EQ.0) GO TO 974
      DO 972 I=1,NTT
        INDFT(TEAR(I))=(NPINP+I-1)*NVAR+1
 972  CONTINUE
C
 974  DIMFT=(NPINP+NTT)*NVAR
      IF(DIMFT.GT.DIMFTM) DIMFTM=DIMFT
      IF(NNOD.GT.NNODM) NNODM=NNOD
      IF(NUM.GT.NUMM) NUMM=NUM
      IF(NU.GT.NUUM) NUUM=NU
      IF(NSM.GT.NSMM) NSMM=NSM
      IF(NTT.GT.NTTM) NTTM=NTT
      IF(NPINP.GT.NPINPM) NPINPM=NPINP
      IF(NPOUT.GT.NPOUTM) NPOUTM=NPOUT
      IF(NTM.GT.NTMM) NTMM=NTM
      IF(NVAR.GT.NVARM) NVARM=NVAR
      NVT=NVAR*NTM
      IF(NVT.GT.NVTM) NVTM=NVT
C
C **WRITE TEARS AND UNIT ORDER FOR EACH NODE
C     PAUSE 13
C
C    WRITE(9,*) NPLT
      WRITE(IWP,3000) NPLT
      DO 973 NOD=1,NNOD
        WRITE(IWP,3001) NOD
        N1=1
        IF(NOD.NE.1) N1=INDT(NOD-1)+1
        N2=INDT(NOD)
        NXXX=0
        IF((N2-N1).LT.0) WRITE(IWP,3002) NXXX
        IF((N2-N1).GE.0) WRITE(IWP,3002) (TEAR(I),I=N1,N2)
        N1=1
        IF(NOD.NE.1) N1=INDORD(NOD-1)+1
        N2=INDORD(NOD)
        WRITE(IWP,3003) (ORDUNT(I),I=N1,N2)
        WRITE(IWP,3004)
 973  CONTINUE
 3000 FORMAT(20X,'PLANT NUMBER',I4/20X,16(1H*)/20X,16(1H*)/)
 3001 FORMAT(20X,'NODE NUMBER',I4/20X,15(1H*))
 3002 FORMAT(5X,'TEARS',20I4)
 3003 FORMAT(5X,'UNIT ORDER'/10X,20(15I4/))
 3004 FORMAT(/)
C
C
C *WRITE OUTPUT FOR NEXT PHASE
C
      N1=INDSV(NSM)
      N2=INDISV(NSM)
      WRITE(IW,2000) NPLT,NNOD,NTT,NU,NSM,NUM,NOPTM,NPINP,NPOUT
      WRITE(IW,2000) (INDORD(I),I=1,NNOD)
      WRITE(IW,2000) (ORDUNT(I),I=1,NU)
      WRITE(IW,2000) (INDT(I),I=1,NNOD)
      IF(NTT.GT.0) WRITE(IW,2000) (TEAR(I),I=1,NTT)
      WRITE(IW,2000) (INDSV(I),I=1,NSM)
      IF(N1.GT.0) WRITE(IW,2000) (STRVEC(I),I=1,N1)
      WRITE(IW,2000) (INDISV(I),I=1,NSM)
      IF(N2.GT.0) WRITE(IW,2000) (INVSV(I),I=1,N2)
      WRITE(IW,2000) (PLINP(I),I=1,NPINP)
      WRITE(IW,2000) (PLOUT(I),I=1,NPOUT)
      WRITE(IW,2000) (STRM(I),I=1,NUM)
      WRITE(IW,2000) (INDPTH(I),I=1,NSM)
      IF(DIMPT.GT.0) WRITE(IW,2000) (PTHVEC(I),I=1,DIMPT)
      WRITE(IW,2000) (INDNP(I),I=1,NNOD)
      IF(NPTH.GT.0) WRITE(IW,2000) (COEF(I),I=1,NPTH)
      !write(*,*)' NSM',NSM
      WRITE(IW,'(16I5)') (INDVAL(I),I=1,NSM)
      !WRITE(*,'(16I5)') (INDVAL(I),I=1,NSM)
      WRITE(IW,'(16I5)') (INDFT(I),I=1,NSM)
      !WRITE(*,'(16I5)') (INDFT(I),I=1,NSM)
C
      GO TO 4
C
  980 CONTINUE
      CLOSE(IW)
      CLOSE(IWP)
      CLOSE(IR)
C      write(*,4001)
      WRITE(DiagFile,4001)
 4001 FORMAT('The flowsheet has been decomposed and the calculation'
     *' order established.')
      result = COMMITQQ(DiagFile)
      ExitValue = -1
      RETURN

9990  continue
C     This is the error trap for errors that occur when a file is
C     opened.
      WRITE(DiagFile,*)
     *'An error occurred when opening file '//JobPath(1:LENG)//FILENAME
      ExitValue = 20
      result = COMMITQQ(DiagFile)
      RETURN

9991  continue
C     This is the error trap for errors that occur when a node has too
C     many cycles.
      WRITE(DiagFile,*)
     *'An error occurred when opening file '//JobPath(1:LENG)//FILENAME
      result = COMMITQQ(DiagFile)
      ExitValue = 22
      CLOSE(IW)
      CLOSE(IWP)
      CLOSE(IR)
      RETURN

9999  continue
      WRITE(DiagFile,*)'An error occured when reading data for the order
     *ing phase.'
      result = COMMITQQ(DiagFile)
      ExitValue = 21
      RETURN
      END
