"Job name","Marble"
"Flowsheet",#TRUE#
"System data",#TRUE#
"Model data",#TRUE#
"System input data",#FALSE#
"Size data",#FALSE#
"G-class distribution",#FALSE#
"Liberation data",#FALSE#
"Ljubljana model",#FALSE#
"Beta function liberation model",#FALSE#
"S-class distribution",#FALSE#
"Washability data",#FALSE#
"System data needed",#FALSE#
"Model parameter data",#FALSE#
"Unit parameters needed",#FALSE#
"Output format",#FALSE#
"SIMOP data",#FALSE#
