C*******************	UNITREPS.FOR	  *****************************C
C                                                                      C
C          MODSIM   MODULAR SIMULATOR FOR ORE DRESSING PLANTS          C
C                                                                      C
C  THIS FILE CONTAINS REPORT WRITERS FOR USER SUPPLIED MODELS	       C
C  FOR MODSIM							       C
C  This file is from Claudio schneider.                                C
C  MODSIM  (C) RP KING  JOHANNESBURG  1985                             C
C                                                                      C
C**********************************************************************C
C
      SUBROUTINE RSEGB(TMSF,TMS1,TMS2,TMS3,FEED,OUT1,OUT2,OUT3,DER1,DER2
     *,DER3,NDC,NGC,NSC,WTR,WTR1,WTR2,WTR3,SIZE,PARAM,PPROP,INDPP,FL,NPP
     *,GRDM,GRDV,NMIN,NGCM)
C     ******************************************************************
      REAL  FEED(NDC,NGC,NSC),OUT1(NDC,NGC,NSC),OUT2(NDC,NGC,NSC)
      REAL  OUT3(NDC,NGC,NSC)
      REAL  DER1(NDC,NGC,NSC),DER2(NDC,NGC,NSC),DER3(NDC,NGC,NSC)
      REAL PARAM(*),PPROP(1)
      REAL SIZE(1),GRDM(NGCM,NMIN),GRDV(NGCM,NMIN)
      INTEGER FL,INDPP(NPP,2)

      COMMON /MODELDAT/NUNIT
C
C     MODEL TO DESCRIBE SEGREGATION IN SURGE BINS AT ROSSING URANIUM LTD
C
C     PARAMETERS IN ORDER
C     *******************
C 1.....SMALL SIZE ASYMPTOTE
C 2.....RECOVERY OF INTERMEDIATE SIZES
C 3.....CRITICAL SIZE
C 4.....SLOPE OF LOGARITHMIC PORTION
      NOPAR=4
      B1 = PARAM(1)
      B2 = PARAM(2)
      B3 = PARAM(3)
      B4=PARAM(4)
      TMS1 = 0.0
      DO 20 I = 1,NDC
      IF (SIZE(I).LE.0.01) REC = B1
      IF(SIZE(I).GT.0.01.AND.SIZE(I).LE.B3)REC=B2
      IF (SIZE(I).GT.B3) REC = B2 - B4*ALOG(SIZE(I)/B3)
      DO 20 J = 1,NGC
      DO 20 K = 1,NSC
      OUT2(I,J,K) = REC*FEED(I,J,K)
      OUT1(I,J,K) = FEED(I,J,K) - OUT2(I,J,K)
      DER2(I,J,K) = REC
      DER1(I,J,K) = 1.0 - REC
      TMS1 = TMS1 + OUT1(I,J,K)
  20  CONTINUE
      TMS2 = TMSF - TMS1
      WTR1 = B2*WTR
      WTR2=WTR-WTR1
      FL = 1
	LU=8
	ITERM=5
	CALL HEADER(LU,ITERM,NUNIT,'SEGREGATING BIN',15,'SEGB')
	WRITE(LU,1000)(PARAM(I),I=1,NOPAR)
 1000   FORMAT(/' PARAMETERS:',/' RECOVERY OF FINES ',F6.3,/
     *  ' RECOVERY OF INTERMEDIATE SIZES ',F6.3,/
     *  ' CRITICAL SIZE ',F6.3,/
     *  ' LOG SLOPE ',F6.3)
	TREC=TMS2/TMSF
	WRITE(LU,1001)TREC
 1001   FORMAT(' RECOVERY OF SOLIDS TO FINER STREAM ',F6.3)
      RETURN
      END
C
C
      SUBROUTINE RUMIL(TMSF,TMS1,TMS2,TMS3,FEED,OUT1,OUT2,OUT3,DER1,DER2
     *,DER3,NDC,NGC,NSC,WTR,WTR1,WTR2,WTR3,SIZE,PARAM,PPROP,INDPP,FL,NPP
     *,GRDM,GRDV,NMIN,NGCM)
C     ******************************************************************
C  MODEL FOR A BALL MILL USING THREE PERFECTLY MIXED REGIONS IN SERIES.
C  NO CLASSIFICATION BETWEEN STAGES, POST-CLASSIFICATION OPTIONAL.
C  PARAMETERS:
C     1....RESIDENCE TIME IN THE MILL'S FIRST PERFECT MIXED REGION.
C     2....RESIDENCE TIME IN THE MILL'S SECOND PERFECT MIXED REGION.
C     3....RESIDENCE TIME IN THE MILL'S THIRD PERFECT MIXED REGION.
C     4....FUNCTIONAL FORM CHOSEN:
C            1 = 3 PAR. BREAK. & 4 PAR. RATE W/O POST CLASSIFICATION
C            2 = 3 PAR. BREAK. & 4 PAR. RATE W/  POST CLASSIFICATION
C            3 = 4 PAR. BREAK. & 4 PAR. RATE W/  POST CLASSIFICATION
C
      REAL FEED(NDC,NGC,NSC)
      REAL OUT1(NDC,NGC,NSC),OUT2(NDC,NGC,NSC),OUT3(NDC,NGC,NSC)
      REAL DER1(NDC,NGC,NSC),DER2(NDC,NGC,NSC),DER3(NDC,NGC,NSC)
      REAL GRDM(NGCM,NMIN),GRDV(NGCM,NMIN)
      REAL SIZE(NDC),PARAM(*),PPROP(1)
      INTEGER INDPP(NPP,2),FL
      COMMON /MODELDAT/NUNIT
      COMMON/SCALEUP/OVFILL

      LOGICAL LJUBLJANA, AM_MODEL
      COMMON /LINCOR/PHIA,LJUBLJANA,AM_MODEL

      EXTERNAL SU1,SU2,SU3
      EXTERNAL BU1,BU2,BU3
      EXTERNAL CU0,CU2,CU3

	IF (NINT(PARAM(5)) .EQ. 0) Then
        LJUBLJANA = .FALSE.
        AM_MODEL = .FALSE.
      ELSE IF (NINT(PARAM(5)) .EQ. 1) Then
        LJUBLJANA = .TRUE.
        AM_MODEL = .FALSE.
      ELSE IF (NINT(PARAM(5)) .EQ. 2) Then
        LJUBLJANA = .FALSE.
        AM_MODEL = .TRUE.
      END IF
C
      MAXIT = 25
      OVFILL=1.0
      NFUNC=PARAM(4)
      SUMTAU=PARAM(1)+PARAM(2)+PARAM(3)
      DO 5 I=1,NDC
	DO 5 J=1,NGC
	  DO 5 K=1,NSC
	    DER1(I,J,K)=1.0
    5 CONTINUE
      DTBDF=0.0
C
C  CALCULATE PRODUCT OF FIRST PERFECT MIXED REGION
C
      NCALL=1
      TAU=PARAM(1)
      IF(NFUNC.EQ.1)
     *CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.2)
     *CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.3)
     *CALL PMMILL(FEED,OUT3,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
C
C  CALCULATE PRODUCT OF SECOND PERFECT MIXED REGION
C
      NCALL=2
      TAU=PARAM(2)
      IF(NFUNC.EQ.1)
     *CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.2)
     *CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.3)
     *CALL PMMILL(OUT3,OUT2,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
C
C  CALCULATE PRODUCT OF THIRD PERFECT MIXED REGION
C
      NCALL=3
      IF(NFUNC.EQ.1) THEN
      TAU = PARAM(3)
      CALL PMMILL(OUT2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU1,BU1,GRDM,NGCM,NMIN,NCALL,DER3)
      FFLOW = TMSF
      TMS1 = 0.0
      DO 10 I=1,NDC
	DO 10 J=1,NGC
	  DO 10 K=1,NSC
	  TMS1 = TMS1 + OUT1(I,J,K)
  10  CONTINUE
      TAUPRIME=PARAM(3)
      GOTO 35
      ENDIF
C
C  LAST STAGE HAS POST-CLASSIFICATION
C
      DO 15 I=1,NDC
	DO 15 J=1,NGC
	  DO 15 K=1,NSC
	  DER2(I,J,K) = OUT2(I,J,K)
   15 CONTINUE
      IT=0
   20 CONTINUE
      TAU=TAUPRIME
      IF(NFUNC.EQ.2)
     *CALL PMMILL(DER2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU2,BU2,GRDM,NGCM,NMIN,NCALL,DER3)
      IF(NFUNC.EQ.3)
     *CALL PMMILL(DER2,OUT1,DER1,NDC,NGC,NSC,SIZE,TAU,DTBDF,PPROP,
     *INDPP,NPP,SU3,BU3,GRDM,NGCM,NMIN,NCALL,DER3)
      GFLOW = 0.0
      FFLOW = 0.0
      DO 30 I=1,NDC
	IF(NFUNC.EQ.2) CALL CU2(I,SIZE(I),C)
	IF(NFUNC.EQ.3) CALL CU3(I,SIZE(I),C)
	DO 30 J=1,NGC
	  DO 30 K=1,NSC
	    FFLOW = FFLOW + OUT1(I,J,K)*(1.0-C)
	    GFLOW = GFLOW + OUT1(I,J,K)
	    DER2(I,J,K) = OUT2(I,J,K) + OUT1(I,J,K)*C
   30 CONTINUE
      GBYF = GFLOW/FFLOW
      IT = IT + 1
      RES = ABS(PARAM(3) - TAUPRIME*GBYF)
      IF(RES.LE.1E-5) GOTO 35
      IF(IT.GE.MAXIT) GOTO 35
      TAUPRIME = PARAM(3)/GBYF
      GOTO 20
   35 CONTINUE
C
C  ACCUMULATE HOLDUPS OF FIRST TWO STAGES 
C                                                     
      DO 40 I=1,NDC
      DO 40 J=1,NGC
      DO 40 K=1,NSC
	OUT2(I,J,K)=OUT2(I,J,K)*PARAM(2)+OUT3(I,J,K)*PARAM(1)
   40 CONTINUE
C  
C  CALCULATE PRODUCT OF POSTCLASSIFIER IN THIRD STAGE 
C  AND SAVE MILL PRODUCT IN OUT3
C
      TMS1 = 0.0
      DO 50 I=1,NDC
	IF(NFUNC.EQ.1) CALL CU0(I,SIZE(I),C)
	IF(NFUNC.EQ.2) CALL CU2(I,SIZE(I),C)
	IF(NFUNC.EQ.3) CALL CU3(I,SIZE(I),C)
	DO 50 J=1,NGC
	  DO 50 K=1,NSC
	    OUT3(I,J,K) = OUT1(I,J,K)
	    OUT1(I,J,K)=OUT1(I,J,K)*(1.0-C)
	    TMS1 = TMS1 + OUT1(I,J,K)
   50 CONTINUE
      WTR1=WTR
      FL=0
C
C  WRITE THE REPORT FILE.
C  OBTAIN MILL HOLDUP
C
      LU = 8
      C1=PARAM(3)/TAUPRIME
      DO 60 I=1,NDC
	DO 60 J=1,NGC
	  DO 60 K=1,NSC 
	    OUT2(I,J,K) = (OUT2(I,J,K)+OUT3(I,J,K)*PARAM(3)/C1)/SUMTAU           
   60 CONTINUE
	TFLOW=(GFLOW)*3.6
	ITERM=5
	CALL HEADER(LU,ITERM,NUNIT,'BALL MILL',9,'UMIL')
	TONS=TMSF*3.6
	HU=TMSF*60.0*SUMTAU/1000.0
C       WRITE(LU,1005)
 1005   FORMAT(/' Mill has 3 well-mixed segments in series without class
     *ification.')
	WRITE(LU,1006) PARAM(1),PARAM(2),PARAM(3),TAUPRIME,TONS,HU,
     *TFLOW
 1006   FORMAT(/' PARAMETERS:'/
     *'   Residence time in mill region 1 ',T46,F7.2,' minutes.'/
     *'   Residence time in mill region 2 ',T46,F7.2,' minutes.'/
     *'   Residence time in mill region 3 ',T46,F7.2,' minutes.'/
     *'   Calculated residence time in mill region 3 ',
     *    T46,F7.2,' minutes.'/
     *'   Calculated tonnage through mill ',T46,F8.2,' tons/hr.'/
     *'   Calculated hold up in mill ',T46,F8.2,' tons.'/
     *'   Calculated circulating load region 3 ',T46,F8.2,' tons/hr.')
	IF(NFUNC.EQ.1) WRITE(LU,1007)
 1007   FORMAT(/' 3 PARAMETER BREAKAGE & 4 PARAMETER RATE '
     */         ' WITHOUT POST CLASSIFICATION USED'/)
	IF(NFUNC.EQ.2) WRITE(LU,1008)
 1008   FORMAT(/' 3 PARAMETER BREAKAGE & 4 PARAMETER RATE '
     */         ' WITH POST CLASSIFICATION USED'/)
	IF(NFUNC.EQ.3) WRITE(LU,1009)
 1009   FORMAT(/' 4 PARAMETER BREAKAGE & 4 PARAMETER RATE '
     */         ' WITH POST CLASSIFICATION USED'/)
	IF(NINT(PARAM(5)).EQ.1) WRITE(LU,'(
     *  '' Ljubljana liberation model was used''/)')
	IF(NINT(PARAM(5)).EQ.0) WRITE(LU,'(
     *  '' Liberation was not modeled''/)')
	IF(NINT(PARAM(5)).EQ.2) WRITE(LU,'(
     *  '' Beta function liberation model was used''/)')
	CALL PARTSZ(SIZE,FEED,NDC,NGC,NSC,DER2,DER3,DER1)
	WRITE(LU,1050)
 1050   FORMAT(/5X,'Size distribution in FEED')
	CALL WRSZDN(DER2,DER3,NDC,3,LU)
C
C  FIND THE 80% PASSING SIZE IN THE FEED.
	CALL PASSSZ(DER2,DER3,NDC,0.8,PSIZEF)
C
	CALL PARTSZ(SIZE,OUT1,NDC,NGC,NSC,DER2,DER3,DER1)
	WRITE(LU,1051)
 1051   FORMAT(/5X,'Size distribution in PRODUCT')
	CALL WRSZDN(DER2,DER3,NDC,3,LU)
C
C  FIND THE 80% PASSING SIZE IN THE PRODUCT.
	CALL PASSSZ(DER2,DER3,NDC,0.8,PSIZEP)
C
	CALL PARTSZ(SIZE,OUT2,NDC,NGC,NSC,DER2,DER3,DER1)
	WRITE(LU,1052)
 1052   FORMAT(/5X,'Size distribution in HOLDUP')
	CALL WRSZDN(DER2,DER3,NDC,3,LU)

	PSIZEP=PSIZEP*1.0E6
	PSIZEF=PSIZEF*1.0E6
	POWERF=10.0*(1.0/SQRT(PSIZEP)-1.0/SQRT(PSIZEF))
	POWERF=POWERF*TONS
	WRITE(LU,1053) PSIZEF,PSIZEP,POWERF
 1053   FORMAT(/' 80% passing size in feed   ',T45,F8.1,' microns'/
     *          ' 80% passing size in product',T45,F8.1,' microns'/
     *  ' What is the Bond work index for the ore in kWhr/ton?.......'/
     *          ' Power required = ',F8.1,'x W.I.  = ....... kW'/)
C
C    CALCULATE CORRESPONDENT LIBERATION SPECTRA
C    ******************************************
C
      WS1 = 0.0
      WS2 = 0.0
      WS3 = 0.0
      DO 70 J=1,NGC
	DER1(1,J,1) = 0.0
	DER2(1,J,1) = 0.0
	DER3(1,J,1) = 0.0
	DO 80 I=1,NDC
	DO 80 K=1,NSC
	  DER1(1,J,1) = DER1(1,J,1) + OUT1(I,J,K)                   
	  DER2(1,J,1) = DER2(1,J,1) + OUT2(I,J,K)                   
	  DER3(1,J,1) = DER3(1,J,1) + FEED(I,J,K)                  
   80   CONTINUE
	WS1 = WS1 + DER1(1,J,1)
	WS2 = WS2 + DER2(1,J,1)
	WS3 = WS3 + DER3(1,J,1)
   70 CONTINUE
      DO 90 J=1,NGC
	DER1(1,J,1) = DER1(1,J,1)/WS1  
	DER2(1,J,1) = DER2(1,J,1)/WS2  
	DER3(1,J,1) = DER3(1,J,1)/WS3     
   90 CONTINUE    
      WRITE(LU,1054)
 1054 FORMAT(//5x' Liberation spectra in UMILL'//
     *' G-Class       Fractional Distribution'/
     *'              FEED      HOLDUP    PRODUCT'//)
      DO 100 J=1,NGC
	WRITE(LU,1055) J,DER3(1,J,1),DER2(1,J,1),DER1(1,J,1)
  100 CONTINUE
 1055 FORMAT(3X,I3,7X,F5.3,5X,F5.3,5X,F5.3)      
C
      RETURN
      END
