"Job name","mill"
"Flowsheet",#TRUE#
"System data",#TRUE#
"Model data",#TRUE#
"System input data",#TRUE#
"Size data",#TRUE#
"G-class distribution",#TRUE#
"Liberation data",#TRUE#
"Ljubljana model",#FALSE#
"Beta function liberation model",#FALSE#
"S-class distribution",#TRUE#
"Washability data",#FALSE#
"System data needed",#TRUE#
"Model parameter data",#FALSE#
"Unit parameters needed",#TRUE#
"Output format",#FALSE#
"SIMOP data",#TRUE#
